### PR TITLE
i18n AMO link

### PR DESCRIPTION
**Pull request by Gitoffthelawn**

### CODE REVIEW

**Comment by dvnlgls** [comment]
@Gitoffthelawn Can you please tell me what's new with the url you updated? They both seem to resolve to what's in the master branch. Does this somehow affect people who don't use en-us locale? Thanks.

**Comment by Gitoffthelawn** [comment]
Hi Devin. Yes, it's for use outside of the en-us locale (and will still work for the en-us locale).  The URL will now appropriately resolve to the correct locale.  With the previous URL (before the pull request), the page for the en-us locale would always get opened, regardless of the user's locale.

**Comment by dvnlgls** [comment]
@Gitoffthelawn Thanks for catching this and your contribution to an obscure piece of software!

**Comment by Gitoffthelawn** [comment]
You're welcome. And thanks for creating useful obscure software. Some of the my favourite software is the most obscure!

**Pull request merged**
